### ISSUE TITLE
Cant run celest start

### ISSUE THREAD

**Issue by starklord** [celest-dev/celest#23] opened 2024-01-27 15:16 UTC
Hi im testing celest on windows 11 with the intel x64 installer, but i cant run celest start
it says:
Starting Celest...
An unexpected error occurred. A crash report has been sent to the Celest team.

![Screenshot 2024-01-27 101238](https://github.com/celest-dev/celest/assets/18214474/b5286e12-73b0-48d5-bbc0-52a9811e8e14)

**Comment by dnys1** [comment] 2024-01-27 16:29
Hi @starklord, thanks for creating this issue. I'm looking at it now and it seems to be due to path handling on Windows. Is there anything unique about your Windows setup that may help me at reproducing the issue?

**Comment by starklord** [comment] 2024-01-27 16:38
I dont think there is something particular installed in my machine but... the first i did was run flutter upgrade --force and I upgraded to the last flutter and dart versions: Flutter 3.16.9 and Dart 3.2.6
I also restarted my machine without success.
I have a laptop with celest runing well but that is a linux machine.

**Comment by dnys1** [comment] 2024-01-27 16:39
Sounds good. Thanks for the additional info! Looking into it now.

**Comment by dnys1** [comment] 2024-01-27 18:59
Hi @starklord, I've pushed a release which fixes this. You can run `celest upgrade` to get the changes.

Would you be able to retry running `celest start` after and let me know if it's fixed?

**Comment by starklord** [comment] 2024-01-27 20:00
Hi @dnys1 its working like a charm! ty!, now ill continue testing...

**Comment by dnys1** [comment] 2024-01-27 20:01
Awesome! I will close this issue for now, but please let me know if you face any more issues.

**Closed by dnys1** 2024-01-27 20:01 UTC
Labels: bug

**Comment by blaqshyd** [comment] 2024-10-18 02:30
Having the same issue right now with v1.5.0 @dnys1 

Log: An unexpected error occurred. A crash report has.
ID: 34c154c7b1324f108405625c1e3ae16d

**Comment by dnys1** [comment] 2024-10-18 02:34
@blaqshyd its not finding sqlite3 but that shouldn’t typically be an issue. I can see what’s going wrong in the morning, but in the meantime could you try installing sqlite3 from your package manager?

**Comment by blaqshyd** [comment] 2024-10-18 02:39
> @blaqshyd its not finding sqlite3 but that shouldn’t typically be an issue. I can see what’s going wrong in the morning, but in the meantime could you try installing sqlite3 from your package manager?

![Screenshot from 2024-10-18 03-38-01](https://github.com/user-attachments/assets/15927bee-e5ac-4545-8c1d-ffa41c796ebe)
I definitely have that installed on my machine @dnys1

**Comment by dnys1** [comment] 2024-10-18 02:41
Roger that. I’ll take a closer look and keep you posted 👍

**Comment by blaqshyd** [comment] 2024-10-18 02:46
Looking forward to your response. Thanks

**Comment by dnys1** [comment] 2024-10-18 03:45
@blaqshyd  Fixed :-) there was a similar issue in `upgrade` on linux so I would recommend downloading from the website but `celest upgrade` should work again going forward.

**Comment by blaqshyd** [comment] 2024-10-19 15:29
Yes, I noticed the issue with upgrade and had to manually install the v1.0.5 but I'll re-install now and see if that works for me. Do I need to run `celest uninstall` first or just download and install v1.0.6+1 that I just downloaded @dnys1

**Comment by blaqshyd** [comment] 2024-10-19 15:47
It works now. Thank you @dnys1
